### PR TITLE
New UI(s), remove V4 and more.

### PR DESCRIPTION
**Pull request by f1shy-dev**
This PR adds:

- New Main Menu
- New Play Menu GUI
- New Options screen
- Removes V4

Solves #64 and #56

### CODE REVIEW

**Comment by w1wwwwww** [comment]
imagine having failing checks

**Comment by f1shy-dev** [comment]
> imagine having failing checks
shhhhhhhhhh

**Comment by w1wwwwww** [comment]
> 
> 
> > imagine having failing checks
> 
> shhhhhhhhhh _we dont talk bout that_

ok

**Comment by jerbear2008** [comment]
Wait, 'remove V4'? Was the paid version available on GitHub?

**Comment by w1wwwwww** [comment]
no, that was a form of level compression that didnt work

**Pull request merged**
