### PR TITLE
Updated Markdown Files

### PR DESCRIPTION
**Pull request by Just-a-Unity-Dev**
**Detailed Description of What I Did**
- Redirected the CODE OF CONDUCT to `master`
- Redirected the CONTRIBUTERS AGREEMENT to `master`
- Added a thumbnail (feel free to change it)

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
merge this one if you are planning to merge the other

**Comment by Just-a-Unity-Dev** [comment]
also, this is the 69TH Pull Request

**Comment by f1shy-dev** [comment]
This seems great, but I'm changing the home screen/main menu of the game in my PR soon, so I'm not sure if we should keep that banner.

I could try make one.

**Comment by f1shy-dev** [comment]
*I have opened a PR on your PR.

**Pull request merged**
